ceos_image_filename: cEOS-lab-4.29.10.1M.tar
ceos_image_orig: ceosimage:4.29.10.1M
ceos_image: ceosimage:4.29.10.1M-1
# Please update ceos_image_url to the actual URL of the cEOS image file in your environment. If the cEOS image file
# is not available on test server, the cEOS image file will be downloaded from this URL.
# The ceos_image_url can be a string as single URL or a list of strings as multiple URLs. If it is a list, the code
# logic will automatically try each URL in the list
ceos_image_url:
  - "http://example1.com/cEOS-lab-4.29.10.1M.tar"
  - "http://example2.com/cEOS-lab-4.29.10.1M.tar"
skip_ceos_image_downloading: true
